Create Button disabled
nikita-ng/blockapps-ba pull request #1
Opened 2017-11-16 16:28 UTC by nikita-ng

2017-11-16 16:43 UTC, liorsaar1 commented on ui/src/scenes/Projects/components/ProjectCreate/index.js
> +      if(this.state.name && this.state.description && this.state.price && this.state.targetDelivery && this.state.spec) {
1. please add comments

2017-11-16 16:48 UTC, liorsaar1 requested changes
1. please add comments
2. check for empty fields (null, white spaces)

2017-11-17 12:28 UTC, nikita-ng commented
Please review the code. Changes has been done as said.

2017-11-17 15:28 UTC, liorsaar1 requested changes

2017-11-17 15:28 UTC, liorsaar1 commented on ui/src/scenes/Projects/components/ProjectCreate/index.js
> +        this.state.description &&
please refactor.

this.enable = isFormValid(this.state);

function isFormValid(state) {
  if isEmpty(state.name) return false;
  if isEmpty(state.description) return false;
  ...
  ...
}

2017-11-17 19:17 UTC, nikita-ng commented
Refactoring done.

2017-11-17 19:23 UTC, liorsaar1 requested changes

2017-11-17 19:23 UTC, liorsaar1 commented on ui/src/scenes/Projects/components/ProjectCreate/index.js
> +  }
state.name.trim()  should be inside isEmpty()

2017-11-17 19:35 UTC, nikita-ng commented
Updation in isEmpty().

2017-11-17 19:42 UTC, liorsaar1 approved these changes

2017-11-17 19:42 UTC, merged